MODULE=alu

.PHONY: sim
sim: waveform.vcd

.PHONY: verilate
verilate: .stamp.verilate

.PHONY: build
build: obj_dir/V$(module)

.PHONY: waves
waves: waveform.vcd
	@echo
	@echo "# WAVES #"
	gtkwave waveform.vcd

waveform.vcd: ./obj_dir/V$(MODULE)
	@echo
	@echo "# SIMULATING #"
	@./obj_dir/V$(MODULE) +verilator+rand+reset+2

./obj_dir/V$(MODULE): .stamp.verilate
	@echo
	@echo "# BUILDING SIM #"
	make -C obj_dir -f V$(MODULE).mk V$(MODULE) 

.stamp.verilate: $(MODULE).sv tb_$(MODULE).cpp
	@echo
	@echo "# RUNNING VERILATOR #"
	verilator -Wall --trace --x-assign unique -x-initial unique -cc $(MODULE).sv --exe tb_$(MODULE).cpp
	@touch .stamp_verilate

.PHONY: lint
lint: $(MODULE).sv
	verilator --lint-only $(MODULE).sv

.PHONY: clean
clean:
	rm -fr .stamp.*;
	rm -fr ./obj_dir
	rm -fr waveform.vcd
	
